Fix/product page
FloydanTheBeast/fake-burrberry-frontend pull request #5
Opened 2017-08-02 10:06 UTC by FloydanTheBeast

2017-08-02 11:11 UTC, evgenyrodionov commented
В 8

2017-08-02 18:22 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28888218-77f12f66-77c8-11e7-9059-6a26a654a393.png)
![image](https://user-images.githubusercontent.com/775692/28888228-833552ee-77c8-11e7-914e-d1ab20a45750.png)
![image](https://user-images.githubusercontent.com/775692/28888241-8f42b8d8-77c8-11e7-9264-1d977cd2cb56.png)
![image](https://user-images.githubusercontent.com/775692/28888252-9812423a-77c8-11e7-80f8-0f247193ae25.png)

2017-08-02 20:13 UTC, FloydanTheBeast commented
Вообщем,выдрочил каждый пиксель

2017-08-03 10:08 UTC, evgenyrodionov commented
Вот тут всё заебись! Кроме текста описания, он съезжает буквально на пиксель. На шиппинг/ретёрнс не обращай внимания, всё ок.

![image](https://user-images.githubusercontent.com/775692/28916985-b0fe5a66-784c-11e7-8c77-a99623e4f756.png)

внизу съехало + цена не тем шрифтом
![image](https://user-images.githubusercontent.com/775692/28917008-c831c826-784c-11e7-9752-db0bb7fdcff6.png)

2017-08-03 10:20 UTC, imevro requested changes
я охуел от твоих дивов и слабой семантики

2017-08-03 10:20 UTC, evgenyrodionov commented on .gitignore
> +.DS_Store
в корне всё равно валяется, удали из репозитория

2017-08-03 10:20 UTC, evgenyrodionov commented on assets/styles/.csscomb.json
> +{
а почему это не в корне

2017-08-03 10:20 UTC, evgenyrodionov commented on assets/styles/main.css
> +	font: 1.25rem "Lora",Helvetica Neue,Helvetica;
почему табами? в кодгайде 2 пробела

2017-08-03 10:20 UTC, evgenyrodionov commented on assets/styles/main.css
> +.product-recommendation-items-first,
бля что за задротское перечисление?

2017-08-03 10:20 UTC, evgenyrodionov commented on assets/styles/main.css
> +	flex-basis: 130px;
и почему флекс-бейсис в пикселях? запрещено же

2017-08-03 10:20 UTC, evgenyrodionov commented on assets/styles/main.css
> +	flex-basis: 130px;
опять же

2017-08-03 10:20 UTC, evgenyrodionov commented on assets/styles/main.css
> +.active-btn {
от общего к частному — кнопка без эктив чаще встречается чем кнопка с эктив

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +      <div class="header-logo">
зачем столько дивов? чем не устраивает header > img?

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +      <div class="product-name">
зачем тут див

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +    <div class="product">
используй section

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          <div class="product-info-main-price">
ааааа сколько дивов

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          <div class="product-info-main-code">
ДИВОВ

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +        <div class="product-delivery-size">
Я В НИХ ТОНУ СКОЛЬКО ДИВОВ ПОЧЕМУ

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          <div><h2 class="product-additional-description-text">description</h2></div>
И ДАЖЕ ТУТ ДИВ? ДИВ В ДИВЕ В ДИВЕ РАДИ h2?

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          <ul class="product-additional-description-text-list">
с сервера не придёт класс

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          woven and breathable fabric that protects against wind and rain.<br />
это абзацы всё, не перенсоы

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          <p class="product-additional-description-hr"></p>
ты назвал класс hr но при этом использовал `<p>` вместо `<hr>`?

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +          <img src="assets/img/triangle.svg" class="product-additional-description-img"/>
в цсс

2017-08-03 10:20 UTC, evgenyrodionov commented on index.html
> +    <div class="footer">
что мешало повесить класс футер на, собственно, футер

2017-08-03 10:22 UTC, evgenyrodionov commented on .gitignore
> +.DS_Store
в смысле файл, не гитигнор

2017-08-03 19:01 UTC, evgenyrodionov commented
Почему коммиты не по формату?

2017-08-03 19:02 UTC, imevro approved these changes

2017-08-03 19:02 UTC, evgenyrodionov commented
делай планшет

2017-08-03 19:06 UTC, merged