Feat/product page
FloydanTheBeast/fake-burrberry-frontend pull request #8
Opened 2017-08-04 16:54 UTC by FloydanTheBeast

Сделал таки планшетную версию,фиксанул немного все,добавил скролл в галерею

2017-08-04 19:34 UTC, evgenyrodionov commented
ПОЧЕМУ БЛЯДЬ КОММИТЫ ДО СИХ ПОР НЕ ПО ФОРМАТУ?

2017-08-04 19:34 UTC, evgenyrodionov commented
блядь пиздец переделывай

2017-08-04 19:35 UTC, imevro commented
и конфликты исправляй

2017-08-04 19:36 UTC, evgenyrodionov commented
ещё и в мастер без моего разрешения смерджил, охуеть

2017-08-04 19:36 UTC, imevro commented
иди чисти

2017-08-05 08:43 UTC, FloydanTheBeast commented
Исправил конфликты с веткой мастер,пофиксил дизайн,отформатировал responsive.css

2017-08-05 08:44 UTC, FloydanTheBeast commented
И да,наконец-то коммит по-формату)))

2017-08-05 09:04 UTC, FloydanTheBeast commented
И кстати,расхождение с макетом из-за того,что в слайдере виден кусок второй картинки,которой нет в макете,плюс в карточках с рекомендациями другой текст,ты сказал на это забить

2017-08-05 15:20 UTC, evgenyrodionov commented
ОТКАТИ МАСТЕР

2017-08-05 15:20 UTC, evgenyrodionov commented
ВЕРНИ ПУЛЛРЕКВЕСТ МОБИЛЬНОЙ В МАСТЕР

2017-08-05 15:21 UTC, evgenyrodionov commented
ЭТОТ ПУЛЛРЕКВЕСТ НАПРАВЬ В БРАНЧ С МОБИЛЬНОЙ

2017-08-05 15:21 UTC, evgenyrodionov commented
Распидорено

![image](https://user-images.githubusercontent.com/775692/28996526-ecd07212-7a0a-11e7-8bc5-66cafdba1c62.png)
![image](https://user-images.githubusercontent.com/775692/28996527-efa141c4-7a0a-11e7-8d96-7e68e9351d98.png)

2017-08-05 17:05 UTC, FloydanTheBeast commented
Вычистил мастер,исправил 2 ошибки в дизайне

2017-08-05 19:37 UTC, evgenyrodionov commented
В футере нет контейнера

![image](https://user-images.githubusercontent.com/775692/28998221-482043b8-7a2e-11e7-9f08-b1aef2f287c7.png)

![image](https://user-images.githubusercontent.com/775692/28998222-58043cee-7a2e-11e7-80cd-0ab9983eafbb.png)

Там похоже вообще сетки нет
![image](https://user-images.githubusercontent.com/775692/28998227-75bb4e80-7a2e-11e7-80d8-6be02cd861e9.png)

2017-08-05 19:37 UTC, evgenyrodionov commented
Зачем бры ставил?
![image](https://user-images.githubusercontent.com/775692/28998241-b20f2a14-7a2e-11e7-90f8-300ab89c4907.png)

2017-08-05 19:41 UTC, imevro requested changes
стиль кода какой-то обдроченный стал

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/main.css
> +  margin: 0 0 49px 0;
что за 49?

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/main.css
> +  height: 10px;
втф

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/main.css
> +  size: 1px;
такое свойство есть?

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/main.css
> +  padding: 0 0 0 0.875rem;
`padding: 0;
padding-left: 0.875rem;`

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/main.css
> +.product-recommendation-item:nth-child(odd) {
задротский селектор

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/main.css
> +.options-country {
нейминг не относится к футеру

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/responsive.css
> +		padding: 0;
откуда 4 пробела взялось

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/responsive.css
> +@media screen and (min-width:0) {
зачем? мобайл-фёст не так работает

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/responsive.css
> +	.img2 {
что это за нейминг по порядку?

2017-08-05 19:41 UTC, evgenyrodionov commented on assets/styles/responsive.css
> +@media screen and (min-width:0) {
зачем ты в отдельный файл вынес, кстати, если всё делается в том же

2017-08-05 19:41 UTC, evgenyrodionov commented on index.html
> +      <div class="product-recommendation">
ставь section для больших секций

2017-08-05 19:41 UTC, evgenyrodionov commented on index.html
> +        <div class="product-more-text">
зачем тут див?

2017-08-05 19:41 UTC, evgenyrodionov commented on index.html
> +      <nav class="footer-nav col-md-3">
не смешивай свои классы и классы сетки

2017-08-05 19:41 UTC, evgenyrodionov commented on index.html
> +      <nav class="footer-nav col-md-3">
на этом и наебался, к слову

2017-08-06 04:50 UTC, FloydanTheBeast commented
В мобильной версии,опять же,расхождения из-за отступа в контейнере

2017-08-06 21:04 UTC, evgenyrodionov commented
Исправь жирный текст

![image](https://user-images.githubusercontent.com/775692/29007060-f0426ef6-7b03-11e7-8954-fc694878dd10.png)

2017-08-06 21:05 UTC, imevro requested changes

2017-08-06 21:05 UTC, evgenyrodionov commented on index.html
> +        <div class="product-recommendation-items row">
говорил же не смешивать свои классы и классы сетки

2017-08-06 21:33 UTC, evgenyrodionov commented
Хотя иди исправляй и объясни мне в личку почему ты должен пройти на следующий этап

2017-08-08 08:11 UTC, imevro requested changes

2017-08-08 08:11 UTC, evgenyrodionov commented on index.html
> +            <div class="col-xs-6 col-md-3"><div class="product-recommendation-item"><a href="#" class="product-recommendation-items-link">
почему 3 открывающих тега на одной строке? пиздец

2017-08-08 08:11 UTC, merged